import { useEffect, useState } from 'react';

// Wails runtime imports (will be generated by wails)
// @ts-ignore
import { Login, SignUp, Logout, GetCurrentUser, IsAuthenticated, GetRooms, GetMyRooms, GetRoom, GetRoomMembers, CreateRoom, JoinRoom, SendMessage, GetMessages, GetDashboardStats, GetTodayGoals, ToggleGoalComplete, GetMyStudyPlans, GetActiveChallenges, GetUserProfile, GetUserStats, SendFriendRequest, GetIncomingFriendRequests, AcceptFriendRequest, RejectFriendRequest, GetFriends } from '../wailsjs/go/main/App';
// @ts-ignore
import { EventsOn, EventsOff } from '../wailsjs/runtime/runtime';

export interface User {
  id: string;
  email: string;
  name: string;
  age: number;
  role: 'student' | 'parent' | 'teacher';
}

export interface Room {
  id: string;
  name: string;
  subject: string;
  description: string;
  owner_id: string;
  is_private: boolean;
  max_members: number;
  is_live: boolean;
}

export interface Message {
  id: string;
  room_id: string;
  user_id: string;
  user_name: string;
  content: string;
  message_type: string;
  created_at: string;
}

export interface DashboardStats {
  study_streak: number;
  total_xp: number;
  weekly_rank: number;
  today_hours: number;
  level?: number;
  weekly_xp?: number;
  gems?: number;
  tokens?: number;
  badges_earned?: number;
}

export interface Goal {
  id: string;
  title: string;
  completed: boolean;
  subject: string;
}

export interface StudyPlan {
  id: string;
  name: string;
  progress: number;
  due_date: string;
}

export interface Challenge {
  id: string;
  title: string;
  participants: number;
  ends_in: string;
  reward: string;
}

// Wails Auth Hook
export function useWailsAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    checkAuth();

    // Listen for auth events
    EventsOn('auth:login', (userData: User) => {
      setUser(userData);
    });

    EventsOn('auth:logout', () => {
      setUser(null);
    });

    return () => {
      EventsOff('auth:login');
      EventsOff('auth:logout');
    };
  }, []);

  const checkAuth = async () => {
    try {
      const isAuth = await IsAuthenticated();
      if (isAuth) {
        const currentUser = await GetCurrentUser();
        setUser(currentUser);
      }
    } catch (error) {
      console.error('Auth check failed:', error);
    } finally {
      setLoading(false);
    }
  };

  const login = async (email: string, password: string) => {
    try {
      const response = await Login(email, password);
      setUser(response.user);
      return response;
    } catch (error) {
      throw error;
    }
  };

  const signup = async (email: string, password: string, name: string, age: number, role: string) => {
    try {
      const response = await SignUp(email, password, name, age, role);
      setUser(response.user);
      return response;
    } catch (error) {
      throw error;
    }
  };

  const logout = async () => {
    // Önce user'ı null yap (hemen görsel geri bildirim için)
    setUser(null);
    try {
      await Logout();
      // auth:logout event listener da setUser(null) çağıracak ama zaten null
    } catch (error) {
      // Even if Logout() fails, user is already null
      throw error;
    }
  };

  return { user, loading, login, signup, logout };
}

// Wails Rooms Hook
export function useWailsRooms(subject: string = '', isTeacher: boolean = false) {
  const [rooms, setRooms] = useState<Room[]>([]);
  const [loading, setLoading] = useState(false);

  const loadRooms = async (subjectFilter?: string) => {
    setLoading(true);
    try {
      const filter = subjectFilter !== undefined ? subjectFilter : subject;
      const data = isTeacher ? await GetMyRooms(filter) : await GetRooms(filter);
      setRooms(data || []);
    } catch (error) {
      console.error('Failed to load rooms:', error);
      setRooms([]);
    } finally {
      setLoading(false);
    }
  };

  const createRoom = async (
    name: string,
    subject: string,
    description: string,
    syllabus: any, // Structured syllabus or null
    isPrivate: boolean,
    maxMembers: number
  ) => {
    try {
      const room = await CreateRoom(name, subject, description, syllabus, isPrivate, maxMembers);
      setRooms(prev => [...prev, room]);
      return room;
    } catch (error) {
      throw error;
    }
  };

  const joinRoom = async (roomId: string) => {
    try {
      await JoinRoom(roomId);
    } catch (error) {
      throw error;
    }
  };

  useEffect(() => {
    // Listen for room events
    EventsOn('room:created', (room: Room) => {
      setRooms(prev => [...prev, room]);
    });

    return () => {
      EventsOff('room:created');
    };
  }, []);

  return { rooms, loading, loadRooms, createRoom, joinRoom };
}

// Wails Messages Hook
export function useWailsMessages(roomId: string | null) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (roomId) {
      loadMessages();
    }

    // Listen for new messages
    EventsOn('message:sent', (message: Message) => {
      if (message.room_id === roomId) {
        setMessages(prev => [...prev, message]);
      }
    });

    return () => {
      EventsOff('message:sent');
    };
  }, [roomId]);

  const loadMessages = async () => {
    if (!roomId) return;
    
    setLoading(true);
    try {
      const data = await GetMessages(roomId);
      setMessages(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('Failed to load messages:', error);
      setMessages([]);
    } finally {
      setLoading(false);
    }
  };

  const sendMessage = async (content: string) => {
    if (!roomId) return;

    try {
      const message = await SendMessage(roomId, content);
      setMessages(prev => [...prev, message]);
      return message;
    } catch (error) {
      throw error;
    }
  };

  return { messages, loading, loadMessages, sendMessage };
}

// Wails Dashboard Hook
export function useWailsDashboard() {
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [goals, setGoals] = useState<Goal[]>([]);
  const [studyPlans, setStudyPlans] = useState<StudyPlan[]>([]);
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [loading, setLoading] = useState(false);

  const loadDashboardData = async () => {
    setLoading(true);
    try {
      const [statsData, goalsData, plansData, challengesData] = await Promise.all([
        GetDashboardStats().catch(() => null),
        GetTodayGoals().catch(() => []),
        GetMyStudyPlans().catch(() => []),
        GetActiveChallenges().catch(() => []),
      ]);

      setStats(statsData);
      setGoals(Array.isArray(goalsData) ? goalsData : []);
      setStudyPlans(Array.isArray(plansData) ? plansData : []);
      setChallenges(Array.isArray(challengesData) ? challengesData : []);
    } catch (error) {
      console.error('Failed to load dashboard data:', error);
      // Set empty arrays on error
      setGoals([]);
      setStudyPlans([]);
      setChallenges([]);
    } finally {
      setLoading(false);
    }
  };

  const toggleGoal = async (goalId: string) => {
    try {
      await ToggleGoalComplete(goalId);
      // Update local state
      setGoals(prev => prev.map(goal => 
        goal.id === goalId ? { ...goal, completed: !goal.completed } : goal
      ));
    } catch (error) {
      console.error('Failed to toggle goal:', error);
      throw error;
    }
  };

  useEffect(() => {
    loadDashboardData();

    // Listen for goal events
    EventsOn('goal-toggled', () => {
      loadDashboardData();
    });

    // Listen for study session events
    EventsOn('activity:studySessionLogged', () => {
      loadDashboardData();
    });

    return () => {
      EventsOff('goal-toggled');
      EventsOff('activity:studySessionLogged');
    };
  }, []);

  return { stats, goals, studyPlans, challenges, loading, loadDashboardData, toggleGoal };
}

// Wails User Profile Hook (for viewing other users' profiles)
export function useWailsUserProfile() {
  const getUserProfile = async (userID: string) => {
    try {
      const profile = await GetUserProfile(userID);
      return profile;
    } catch (error) {
      console.error('Failed to get user profile:', error);
      throw error;
    }
  };

  const getUserStats = async (userID: string) => {
    try {
      const stats = await GetUserStats(userID);
      return stats;
    } catch (error) {
      console.error('Failed to get user stats:', error);
      throw error;
    }
  };

  return { getUserProfile, getUserStats };
}

// Wails Friends Hook
export function useWailsFriends() {
  const [friends, setFriends] = useState<any[]>([]);
  const [incomingRequests, setIncomingRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const loadFriends = async () => {
    setLoading(true);
    try {
      const data = await GetFriends();
      setFriends(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('Failed to load friends:', error);
      setFriends([]);
    } finally {
      setLoading(false);
    }
  };

  const loadIncomingRequests = async () => {
    setLoading(true);
    try {
      const data = await GetIncomingFriendRequests();
      setIncomingRequests(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('Failed to load incoming requests:', error);
      setIncomingRequests([]);
    } finally {
      setLoading(false);
    }
  };

  const sendFriendRequest = async (toUserID: string) => {
    try {
      await SendFriendRequest(toUserID);
      return true;
    } catch (error) {
      console.error('Failed to send friend request:', error);
      throw error;
    }
  };

  const acceptFriendRequest = async (requestID: string) => {
    try {
      await AcceptFriendRequest(requestID);
      await loadFriends();
      await loadIncomingRequests();
      return true;
    } catch (error) {
      console.error('Failed to accept friend request:', error);
      throw error;
    }
  };

  const rejectFriendRequest = async (requestID: string) => {
    try {
      await RejectFriendRequest(requestID);
      await loadIncomingRequests();
      return true;
    } catch (error) {
      console.error('Failed to reject friend request:', error);
      throw error;
    }
  };

  return {
    friends,
    incomingRequests,
    loading,
    loadFriends,
    loadIncomingRequests,
    sendFriendRequest,
    acceptFriendRequest,
    rejectFriendRequest,
  };
}
