package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// AIQuestion represents a question generated by AI
type AIQuestion struct {
	Question      string   `json:"question" bson:"question"`
	Options       []string `json:"options,omitempty" bson:"options,omitempty"` // For multiple choice
	CorrectAnswer string   `json:"correct_answer" bson:"correct_answer"`
	QuestionType  string   `json:"question_type" bson:"question_type"` // "multiple_choice", "short_answer"
}

// StudyPlanComment represents AI assessment of a study session
type StudyPlanComment struct {
	ID              primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID          primitive.ObjectID `json:"user_id" bson:"user_id"`
	StudyPlanID     primitive.ObjectID `json:"study_plan_id" bson:"study_plan_id"`
	ActivityLogID   primitive.ObjectID `json:"activity_log_id" bson:"activity_log_id"`

	// AI-generated content
	Questions         []AIQuestion `json:"questions" bson:"questions"`
	StudentAnswers    []string     `json:"student_answers,omitempty" bson:"student_answers,omitempty"`
	CorrectAnswers    int          `json:"correct_answers" bson:"correct_answers"`
	TotalQuestions    int          `json:"total_questions" bson:"total_questions"`
	ProductivityScore float64      `json:"productivity_score" bson:"productivity_score"` // 0-100
	AIAnalysis        string       `json:"ai_analysis" bson:"ai_analysis"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// StudentReport represents a periodic performance report
type StudentReport struct {
	ID         primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID     primitive.ObjectID `json:"user_id" bson:"user_id"`
	ReportType string             `json:"report_type" bson:"report_type"` // "daily", "weekly", "monthly"
	StartDate  time.Time          `json:"start_date" bson:"start_date"`
	EndDate    time.Time          `json:"end_date" bson:"end_date"`

	// AI-generated analysis
	Summary         string   `json:"summary" bson:"summary"`
	Strengths       []string `json:"strengths" bson:"strengths"`
	WeakAreas       []string `json:"weak_areas" bson:"weak_areas"`
	Recommendations []string `json:"recommendations" bson:"recommendations"`
	OverallScore    float64  `json:"overall_score" bson:"overall_score"`

	// Calculated metrics
	TotalStudyHours       float64 `json:"total_study_hours" bson:"total_study_hours"`
	AvgFocusScore         float64 `json:"avg_focus_score" bson:"avg_focus_score"`
	AvgProductivityScore  float64 `json:"avg_productivity_score" bson:"avg_productivity_score"`
	GoalsCompleted        int     `json:"goals_completed" bson:"goals_completed"`
	MilestonesProgress    float64 `json:"milestones_progress" bson:"milestones_progress"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// RoomAIContext represents AI training data for a study room
type RoomAIContext struct {
	ID primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	RoomID primitive.ObjectID `json:"room_id" bson:"room_id"`

	// Training data from resources
	TrainedResourceIDs []primitive.ObjectID `json:"trained_resource_ids" bson:"trained_resource_ids"`
	TrainingContent    string               `json:"training_content" bson:"training_content"` // Concatenated content
	Syllabus           *Syllabus            `json:"syllabus,omitempty" bson:"syllabus,omitempty"`

	// Conversation history
	MessageCount  int       `json:"message_count" bson:"message_count"`
	LastTrainedAt time.Time `json:"last_trained_at" bson:"last_trained_at"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

// GameQuestion represents a question in an AI-generated game
type GameQuestion struct {
	Question      string   `json:"question" bson:"question"`
	Options       []string `json:"options,omitempty" bson:"options,omitempty"`
	CorrectAnswer string   `json:"correct_answer" bson:"correct_answer"`
	Explanation   string   `json:"explanation,omitempty" bson:"explanation,omitempty"`
	Points        int      `json:"points" bson:"points"`
}

// GameScenario represents a scenario for arcade/racing games
type GameScenario struct {
	ID            string `json:"id" bson:"id"`
	Question      string `json:"question" bson:"question"`
	Context       string `json:"context" bson:"context"`             // "Enemy approaching", "Obstacle ahead"
	CorrectAction string `json:"correct_action" bson:"correct_action"` // "shoot", "jump", "left"
	Difficulty    int    `json:"difficulty" bson:"difficulty"`
}

// PuzzleConfig represents configuration for puzzle games
type PuzzleConfig struct {
	Pieces      int               `json:"pieces" bson:"pieces"`
	ImageURL    string            `json:"image_url" bson:"image_url"`
	Questions   []QuestionUnlock  `json:"questions" bson:"questions"`
}

// QuestionUnlock represents a question that unlocks puzzle pieces
type QuestionUnlock struct {
	Question      string   `json:"question" bson:"question"`
	Options       []string `json:"options,omitempty" bson:"options,omitempty"`
	CorrectAnswer string   `json:"correct_answer" bson:"correct_answer"`
	UnlockPieces  []int    `json:"unlock_pieces" bson:"unlock_pieces"` // Which pieces to unlock
}

// ColorScheme represents visual customization
type ColorScheme struct {
	Primary   string `json:"primary" bson:"primary"`
	Secondary string `json:"secondary" bson:"secondary"`
	Accent    string `json:"accent" bson:"accent"`
	Background string `json:"background" bson:"background"`
}

// PhysicsSettings represents physics configuration for Phaser games
type PhysicsSettings struct {
	Gravity   float64 `json:"gravity" bson:"gravity"`
	Friction  float64 `json:"friction" bson:"friction"`
	Restitution float64 `json:"restitution" bson:"restitution"`
}

// AudioSettings represents audio configuration
type AudioSettings struct {
	MusicEnabled bool    `json:"music_enabled" bson:"music_enabled"`
	SFXEnabled   bool    `json:"sfx_enabled" bson:"sfx_enabled"`
	Volume       float64 `json:"volume" bson:"volume"`
}

// GameConfig represents template-specific configuration
type GameConfig struct {
	Theme   string          `json:"theme" bson:"theme"` // "space", "underwater", "forest"
	Colors  ColorScheme     `json:"colors" bson:"colors"`
	Physics PhysicsSettings `json:"physics,omitempty" bson:"physics,omitempty"`
	Audio   AudioSettings   `json:"audio" bson:"audio"`
}

// PowerUp represents in-game power-ups
type PowerUp struct {
	Type        string `json:"type" bson:"type"` // "time_freeze", "hint", "skip"
	Duration    int    `json:"duration" bson:"duration"`
	Description string `json:"description" bson:"description"`
}

// GameRuleset represents scoring and gameplay rules
type GameRuleset struct {
	TimeLimit    int            `json:"time_limit" bson:"time_limit"`       // seconds (0 = unlimited)
	LivesCount   int            `json:"lives_count" bson:"lives_count"`
	PassingScore int            `json:"passing_score" bson:"passing_score"` // percentage
	BonusPoints  map[string]int `json:"bonus_points,omitempty" bson:"bonus_points,omitempty"` // "speed_bonus", "streak_bonus"
	Penalties    map[string]int `json:"penalties,omitempty" bson:"penalties,omitempty"`
	PowerUps     []PowerUp      `json:"power_ups,omitempty" bson:"power_ups,omitempty"`
}

// AIGame represents an AI-generated educational game
type AIGame struct {
	ID        primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	RoomID    primitive.ObjectID `json:"room_id" bson:"room_id"`
	TeacherID primitive.ObjectID `json:"teacher_id" bson:"teacher_id"`

	// Metadata
	Title       string `json:"title" bson:"title"`
	Description string `json:"description,omitempty" bson:"description,omitempty"`
	Template    string `json:"template" bson:"template"` // "quiz", "arcade-shooter", "racing", etc.
	Version     string `json:"version" bson:"version"`
	Subject     string `json:"subject" bson:"subject"`
	Difficulty  string `json:"difficulty" bson:"difficulty"` // "easy", "medium", "hard"

	// Game content (AI-generated)
	Questions []GameQuestion `json:"questions,omitempty" bson:"questions,omitempty"`
	Scenarios []GameScenario `json:"scenarios,omitempty" bson:"scenarios,omitempty"` // For arcade/racing
	Puzzles   []PuzzleConfig `json:"puzzles,omitempty" bson:"puzzles,omitempty"`     // For puzzle games

	// Configuration
	Config  GameConfig  `json:"config" bson:"config"`
	Ruleset GameRuleset `json:"ruleset" bson:"ruleset"`

	// Multiplayer
	MaxPlayers  int  `json:"max_players" bson:"max_players"`
	Matchmaking bool `json:"matchmaking" bson:"matchmaking"`

	// Distribution
	BundlePath string `json:"bundle_path,omitempty" bson:"bundle_path,omitempty"`
	BundleHash string `json:"bundle_hash,omitempty" bson:"bundle_hash,omitempty"`

	// Stats
	PlayCount int     `json:"play_count" bson:"play_count"`
	AvgScore  float64 `json:"avg_score" bson:"avg_score"`

	// Deprecated fields (kept for backward compatibility)
	GameType  string `json:"game_type,omitempty" bson:"game_type,omitempty"` // Use Template instead
	TimeLimit int    `json:"time_limit,omitempty" bson:"time_limit,omitempty"` // Use Ruleset.TimeLimit
	PassingScore int `json:"passing_score,omitempty" bson:"passing_score,omitempty"` // Use Ruleset.PassingScore

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

// GameResult represents a student's game performance
type GameResult struct {
	ID        primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	GameID    primitive.ObjectID `json:"game_id" bson:"game_id"`
	StudentID primitive.ObjectID `json:"student_id" bson:"student_id"`

	Score          int       `json:"score" bson:"score"` // percentage
	CorrectAnswers int       `json:"correct_answers" bson:"correct_answers"`
	TotalQuestions int       `json:"total_questions" bson:"total_questions"`
	TimeSpent      int       `json:"time_spent" bson:"time_spent"` // seconds
	Passed         bool      `json:"passed" bson:"passed"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// GoalSuggestion represents an AI-generated goal suggestion
type GoalSuggestion struct {
	ID          primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID      primitive.ObjectID `json:"user_id" bson:"user_id"`
	Title       string             `json:"title" bson:"title"`
	Description string             `json:"description" bson:"description"`
	Subject     string             `json:"subject" bson:"subject"`
	Priority    string             `json:"priority" bson:"priority"` // "high", "medium", "low"
	Reasoning   string             `json:"reasoning" bson:"reasoning"` // Why AI suggested this
	AcceptedAt  *time.Time         `json:"accepted_at,omitempty" bson:"accepted_at,omitempty"`
	CreatedAt   time.Time          `json:"created_at" bson:"created_at"`
}
