package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// AIQuestion represents a question generated by AI
type AIQuestion struct {
	Question      string   `json:"question" bson:"question"`
	Options       []string `json:"options,omitempty" bson:"options,omitempty"` // For multiple choice
	CorrectAnswer string   `json:"correct_answer" bson:"correct_answer"`
	QuestionType  string   `json:"question_type" bson:"question_type"` // "multiple_choice", "short_answer"
}

// StudyPlanComment represents AI assessment of a study session
type StudyPlanComment struct {
	ID              primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID          primitive.ObjectID `json:"user_id" bson:"user_id"`
	StudyPlanID     primitive.ObjectID `json:"study_plan_id" bson:"study_plan_id"`
	ActivityLogID   primitive.ObjectID `json:"activity_log_id" bson:"activity_log_id"`

	// AI-generated content
	Questions         []AIQuestion `json:"questions" bson:"questions"`
	StudentAnswers    []string     `json:"student_answers,omitempty" bson:"student_answers,omitempty"`
	CorrectAnswers    int          `json:"correct_answers" bson:"correct_answers"`
	TotalQuestions    int          `json:"total_questions" bson:"total_questions"`
	ProductivityScore float64      `json:"productivity_score" bson:"productivity_score"` // 0-100
	AIAnalysis        string       `json:"ai_analysis" bson:"ai_analysis"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// StudentReport represents a periodic performance report
type StudentReport struct {
	ID         primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID     primitive.ObjectID `json:"user_id" bson:"user_id"`
	ReportType string             `json:"report_type" bson:"report_type"` // "daily", "weekly", "monthly"
	StartDate  time.Time          `json:"start_date" bson:"start_date"`
	EndDate    time.Time          `json:"end_date" bson:"end_date"`

	// AI-generated analysis
	Summary         string   `json:"summary" bson:"summary"`
	Strengths       []string `json:"strengths" bson:"strengths"`
	WeakAreas       []string `json:"weak_areas" bson:"weak_areas"`
	Recommendations []string `json:"recommendations" bson:"recommendations"`
	OverallScore    float64  `json:"overall_score" bson:"overall_score"`

	// Calculated metrics
	TotalStudyHours       float64 `json:"total_study_hours" bson:"total_study_hours"`
	AvgFocusScore         float64 `json:"avg_focus_score" bson:"avg_focus_score"`
	AvgProductivityScore  float64 `json:"avg_productivity_score" bson:"avg_productivity_score"`
	GoalsCompleted        int     `json:"goals_completed" bson:"goals_completed"`
	MilestonesProgress    float64 `json:"milestones_progress" bson:"milestones_progress"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// RoomAIContext represents AI training data for a study room
type RoomAIContext struct {
	ID primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	RoomID primitive.ObjectID `json:"room_id" bson:"room_id"`

	// Training data from resources
	TrainedResourceIDs []primitive.ObjectID `json:"trained_resource_ids" bson:"trained_resource_ids"`
	TrainingContent    string               `json:"training_content" bson:"training_content"` // Concatenated content
	Syllabus           *Syllabus            `json:"syllabus,omitempty" bson:"syllabus,omitempty"`

	// Conversation history
	MessageCount  int       `json:"message_count" bson:"message_count"`
	LastTrainedAt time.Time `json:"last_trained_at" bson:"last_trained_at"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
}

// GameQuestion represents a question in an AI-generated game
type GameQuestion struct {
	Question      string   `json:"question" bson:"question"`
	Options       []string `json:"options,omitempty" bson:"options,omitempty"`
	CorrectAnswer string   `json:"correct_answer" bson:"correct_answer"`
	Explanation   string   `json:"explanation,omitempty" bson:"explanation,omitempty"`
	Points        int      `json:"points" bson:"points"`
}

// AIGame represents an AI-generated educational game
type AIGame struct {
	ID        primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	RoomID    primitive.ObjectID `json:"room_id" bson:"room_id"`
	TeacherID primitive.ObjectID `json:"teacher_id" bson:"teacher_id"`

	Title      string `json:"title" bson:"title"`
	GameType   string `json:"game_type" bson:"game_type"`       // "quiz", "flashcards", "fill_blank", "matching"
	Subject    string `json:"subject" bson:"subject"`
	Difficulty string `json:"difficulty" bson:"difficulty"`     // "easy", "medium", "hard"

	// Game content (AI-generated)
	Questions []GameQuestion `json:"questions" bson:"questions"`

	// Parameters
	TimeLimit    int `json:"time_limit,omitempty" bson:"time_limit,omitempty"` // seconds per question
	PassingScore int `json:"passing_score" bson:"passing_score"`               // percentage

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// GameResult represents a student's game performance
type GameResult struct {
	ID        primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	GameID    primitive.ObjectID `json:"game_id" bson:"game_id"`
	StudentID primitive.ObjectID `json:"student_id" bson:"student_id"`

	Score          int       `json:"score" bson:"score"` // percentage
	CorrectAnswers int       `json:"correct_answers" bson:"correct_answers"`
	TotalQuestions int       `json:"total_questions" bson:"total_questions"`
	TimeSpent      int       `json:"time_spent" bson:"time_spent"` // seconds
	Passed         bool      `json:"passed" bson:"passed"`

	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// GoalSuggestion represents an AI-generated goal suggestion
type GoalSuggestion struct {
	ID          primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID      primitive.ObjectID `json:"user_id" bson:"user_id"`
	Title       string             `json:"title" bson:"title"`
	Description string             `json:"description" bson:"description"`
	Subject     string             `json:"subject" bson:"subject"`
	Priority    string             `json:"priority" bson:"priority"` // "high", "medium", "low"
	Reasoning   string             `json:"reasoning" bson:"reasoning"` // Why AI suggested this
	AcceptedAt  *time.Time         `json:"accepted_at,omitempty" bson:"accepted_at,omitempty"`
	CreatedAt   time.Time          `json:"created_at" bson:"created_at"`
}
