// Wails Go Bindings Type Definitions
export function Greet(name: string): Promise<string>;
export function Login(email: string, password: string): Promise<any>;
export function SignUp(email: string, password: string, name: string, age: number, role: string): Promise<any>;
export function Logout(): Promise<void>;
export function GetCurrentUser(): Promise<any>;
export function IsAuthenticated(): Promise<boolean>;
export function GetRooms(): Promise<any[]>;
export function GetRoom(roomID: string): Promise<any>;
export function CreateRoom(name: string, subject: string, description: string, syllabus: any, isPrivate: boolean, maxMembers: number): Promise<any>;
export function JoinRoom(roomID: string): Promise<void>;
export function SendMessage(roomID: string, content: string): Promise<any>;
export function GetMessages(roomID: string): Promise<any[]>;
export function GetRoomMembers(roomID: string): Promise<any>;
export function UpdateRoomSyllabus(roomID: string, syllabus: any): Promise<any>;
export function UpdateRoomExamDates(roomID: string, examDates: any): Promise<any>;
export function CreateAssignment(roomID: string, title: string, description: string, dueDate: any, totalPoints: number, assignmentType: string): Promise<any>;
export function GetAssignments(roomID: string): Promise<any>;
export function GetAssignment(assignmentID: string): Promise<any>;
export function UpdateAssignment(assignmentID: string, title: string, description: string, dueDate: any, totalPoints: number, assignmentType: string): Promise<any>;
export function DeleteAssignment(assignmentID: string): Promise<void>;
export function GetUserProfile(userID: string): Promise<any>;
export function GetUserStats(userID: string): Promise<any>;
export function SendFriendRequest(toUserID: string): Promise<void>;
export function GetIncomingFriendRequests(): Promise<any>;
export function AcceptFriendRequest(id: string): Promise<void>;
export function RejectFriendRequest(id: string): Promise<void>;
export function GetFriends(): Promise<any>;
export function GenerateSyllabusFromFile(fileContent: string, subject: string, courseName: string): Promise<any>;
export function GenerateSyllabusFromTopics(topics: string[], subject: string, courseName: string): Promise<any>;