// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AcceptFriendRequest(arg1:string):Promise<void>;

export function AddCourseToStudyPlan(arg1:string,arg2:Record<string, any>):Promise<any>;

export function AnswerQuestion(arg1:string,arg2:string,arg3:string):Promise<any>;

export function Chat(arg1:string,arg2:string):Promise<any>;

export function ChatWithRoomAI(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CompleteAssessment(arg1:Record<string, any>):Promise<any>;

export function CreateAssignment(arg1:string,arg2:string,arg3:string,arg4:any,arg5:number,arg6:string,arg7:any):Promise<any>;

export function CreateChild(arg1:string,arg2:string,arg3:string,arg4:number):Promise<any>;

export function CreateGoal(arg1:Record<string, any>):Promise<any>;

export function CreateMilestone(arg1:Record<string, any>):Promise<any>;

export function CreateResource(arg1:string,arg2:Record<string, any>):Promise<any>;

export function CreateRoom(arg1:string,arg2:string,arg3:string,arg4:any,arg5:boolean,arg6:number):Promise<any>;

export function CreateScheduleBlock(arg1:string,arg2:Record<string, any>):Promise<any>;

export function CreateSmartStudyPlan(arg1:Record<string, any>):Promise<any>;

export function CreateStudyPlan(arg1:Record<string, any>):Promise<any>;

export function DeleteAssignment(arg1:string):Promise<void>;

export function DeleteGoal(arg1:string):Promise<void>;

export function DeleteResource(arg1:string):Promise<void>;

export function DeleteScheduleBlock(arg1:string,arg2:string):Promise<void>;

export function DownloadGameBundle(arg1:string):Promise<string>;

export function ExplainTopic(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GenerateAssessmentQuestions(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GenerateDailyGoals():Promise<any>;

export function GenerateGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<any>;

export function GenerateReport(arg1:string):Promise<any>;

export function GenerateSmartStudyPlan(arg1:Record<string, any>):Promise<any>;

export function GenerateSyllabusFromFile(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GenerateSyllabusFromTopics(arg1:Array<string>,arg2:string,arg3:string):Promise<any>;

export function GetActiveChallenges():Promise<Array<backend.Challenge>>;

export function GetActiveStudySession():Promise<any>;

export function GetAssignment(arg1:string):Promise<any>;

export function GetAssignments(arg1:string):Promise<any>;

export function GetChildren():Promise<any>;

export function GetCurrentUser():Promise<any>;

export function GetDashboardStats():Promise<backend.DashboardStats>;

export function GetFriends():Promise<any>;

export function GetGame(arg1:string):Promise<any>;

export function GetGameResults(arg1:string):Promise<any>;

export function GetGameTemplate(arg1:string):Promise<any>;

export function GetGameTemplates():Promise<any>;

export function GetGoals(arg1:any,arg2:any):Promise<any>;

export function GetIncomingFriendRequests():Promise<any>;

export function GetLeaderboard(arg1:string,arg2:number):Promise<any>;

export function GetMessages(arg1:string):Promise<any>;

export function GetMilestones(arg1:any):Promise<any>;

export function GetMyActivity(arg1:string,arg2:number):Promise<any>;

export function GetMyBadges():Promise<any>;

export function GetMyProfile():Promise<any>;

export function GetMyRooms(arg1:string):Promise<any>;

export function GetMyStudyPlans():Promise<any>;

export function GetReport(arg1:string):Promise<any>;

export function GetReports():Promise<any>;

export function GetResources(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetRoom(arg1:string):Promise<any>;

export function GetRoomAIStatus(arg1:string):Promise<Record<string, any>>;

export function GetRoomGames(arg1:string):Promise<any>;

export function GetRoomMembers(arg1:string):Promise<any>;

export function GetRooms(arg1:string):Promise<any>;

export function GetScheduleBlocks(arg1:string):Promise<any>;

export function GetStudyPlanCourses(arg1:string):Promise<any>;

export function GetTodayGoals():Promise<any>;

export function GetUserProfile(arg1:string):Promise<any>;

export function GetUserSchedule():Promise<any>;

export function GetUserStats(arg1:string):Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function IsAuthenticated():Promise<boolean>;

export function JoinRoom(arg1:string):Promise<void>;

export function LogStudySession(arg1:string,arg2:number):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<backend.AuthResponse>;

export function Logout():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function PauseStudySession():Promise<void>;

export function PlayGame(arg1:string,arg2:Array<string>,arg3:number):Promise<any>;

export function RejectFriendRequest(arg1:string):Promise<void>;

export function ResumeStudySession():Promise<void>;

export function SaveTextToDownloads(arg1:string,arg2:string):Promise<string>;

export function SendFriendRequest(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<any>;

export function SetIdleStatus(arg1:boolean):Promise<void>;

export function ShareResource(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SignUp(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<backend.AuthResponse>;

export function StartStudySession(arg1:string,arg2:string):Promise<any>;

export function StopStudySession(arg1:string,arg2:number):Promise<any>;

export function ToggleGoalComplete(arg1:string):Promise<void>;

export function TrainRoomAI(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateAssignment(arg1:string,arg2:string,arg3:string,arg4:any,arg5:number,arg6:string,arg7:any):Promise<any>;

export function UpdateMilestoneProgress(arg1:string,arg2:number):Promise<void>;

export function UpdateMyProfile(arg1:Record<string, any>):Promise<any>;

export function UpdateRoomExamDates(arg1:string,arg2:any):Promise<any>;

export function UpdateRoomSyllabus(arg1:string,arg2:any):Promise<any>;

export function UpdateScheduleBlock(arg1:string,arg2:string,arg3:Record<string, any>):Promise<any>;

export function UpdateStudyPlanProgress(arg1:string,arg2:number):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<any>;
