// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1) {
  return window['go']['main']['App']['AcceptFriendRequest'](arg1);
}

export function AddCourseToStudyPlan(arg1, arg2) {
  return window['go']['main']['App']['AddCourseToStudyPlan'](arg1, arg2);
}

export function AnswerQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2, arg3);
}

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function ChatWithRoomAI(arg1, arg2) {
  return window['go']['main']['App']['ChatWithRoomAI'](arg1, arg2);
}

export function CompleteAssessment(arg1) {
  return window['go']['main']['App']['CompleteAssessment'](arg1);
}

export function CreateAssignment(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateAssignment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateChild(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChild'](arg1, arg2, arg3, arg4);
}

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateMilestone(arg1) {
  return window['go']['main']['App']['CreateMilestone'](arg1);
}

export function CreateResource(arg1, arg2) {
  return window['go']['main']['App']['CreateResource'](arg1, arg2);
}

export function CreateRoom(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateRoom'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateScheduleBlock(arg1, arg2) {
  return window['go']['main']['App']['CreateScheduleBlock'](arg1, arg2);
}

export function CreateSmartStudyPlan(arg1) {
  return window['go']['main']['App']['CreateSmartStudyPlan'](arg1);
}

export function CreateStudyPlan(arg1) {
  return window['go']['main']['App']['CreateStudyPlan'](arg1);
}

export function DeleteAssignment(arg1) {
  return window['go']['main']['App']['DeleteAssignment'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteResource(arg1) {
  return window['go']['main']['App']['DeleteResource'](arg1);
}

export function DeleteScheduleBlock(arg1, arg2) {
  return window['go']['main']['App']['DeleteScheduleBlock'](arg1, arg2);
}

export function DownloadGameBundle(arg1) {
  return window['go']['main']['App']['DownloadGameBundle'](arg1);
}

export function ExplainTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainTopic'](arg1, arg2, arg3);
}

export function ExportAnalyticsCSV(arg1) {
  return window['go']['main']['App']['ExportAnalyticsCSV'](arg1);
}

export function GenerateAssessmentQuestions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAssessmentQuestions'](arg1, arg2, arg3);
}

export function GenerateDailyGoals() {
  return window['go']['main']['App']['GenerateDailyGoals']();
}

export function GenerateGame(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateGame'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function GenerateSmartStudyPlan(arg1) {
  return window['go']['main']['App']['GenerateSmartStudyPlan'](arg1);
}

export function GenerateSyllabusFromFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSyllabusFromFile'](arg1, arg2, arg3);
}

export function GenerateSyllabusFromTopics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSyllabusFromTopics'](arg1, arg2, arg3);
}

export function GetActiveChallenges() {
  return window['go']['main']['App']['GetActiveChallenges']();
}

export function GetActiveStudySession() {
  return window['go']['main']['App']['GetActiveStudySession']();
}

export function GetAssignment(arg1) {
  return window['go']['main']['App']['GetAssignment'](arg1);
}

export function GetAssignments(arg1) {
  return window['go']['main']['App']['GetAssignments'](arg1);
}

export function GetChildren() {
  return window['go']['main']['App']['GetChildren']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGameResults(arg1) {
  return window['go']['main']['App']['GetGameResults'](arg1);
}

export function GetGameStats(arg1) {
  return window['go']['main']['App']['GetGameStats'](arg1);
}

export function GetGameTemplate(arg1) {
  return window['go']['main']['App']['GetGameTemplate'](arg1);
}

export function GetGameTemplates() {
  return window['go']['main']['App']['GetGameTemplates']();
}

export function GetGoals(arg1, arg2) {
  return window['go']['main']['App']['GetGoals'](arg1, arg2);
}

export function GetIncomingFriendRequests() {
  return window['go']['main']['App']['GetIncomingFriendRequests']();
}

export function GetLeaderboard(arg1, arg2) {
  return window['go']['main']['App']['GetLeaderboard'](arg1, arg2);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMilestones(arg1) {
  return window['go']['main']['App']['GetMilestones'](arg1);
}

export function GetMyActivity(arg1, arg2) {
  return window['go']['main']['App']['GetMyActivity'](arg1, arg2);
}

export function GetMyBadges() {
  return window['go']['main']['App']['GetMyBadges']();
}

export function GetMyProfile() {
  return window['go']['main']['App']['GetMyProfile']();
}

export function GetMyRooms(arg1) {
  return window['go']['main']['App']['GetMyRooms'](arg1);
}

export function GetMyStudyPlans() {
  return window['go']['main']['App']['GetMyStudyPlans']();
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetReports() {
  return window['go']['main']['App']['GetReports']();
}

export function GetResources(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResources'](arg1, arg2, arg3);
}

export function GetRoom(arg1) {
  return window['go']['main']['App']['GetRoom'](arg1);
}

export function GetRoomAIStatus(arg1) {
  return window['go']['main']['App']['GetRoomAIStatus'](arg1);
}

export function GetRoomAnalytics(arg1) {
  return window['go']['main']['App']['GetRoomAnalytics'](arg1);
}

export function GetRoomGames(arg1) {
  return window['go']['main']['App']['GetRoomGames'](arg1);
}

export function GetRoomMembers(arg1) {
  return window['go']['main']['App']['GetRoomMembers'](arg1);
}

export function GetRooms(arg1) {
  return window['go']['main']['App']['GetRooms'](arg1);
}

export function GetScheduleBlocks(arg1) {
  return window['go']['main']['App']['GetScheduleBlocks'](arg1);
}

export function GetStudyPlanCourses(arg1) {
  return window['go']['main']['App']['GetStudyPlanCourses'](arg1);
}

export function GetTodayGoals() {
  return window['go']['main']['App']['GetTodayGoals']();
}

export function GetUserProfile(arg1) {
  return window['go']['main']['App']['GetUserProfile'](arg1);
}

export function GetUserSchedule() {
  return window['go']['main']['App']['GetUserSchedule']();
}

export function GetUserStats(arg1) {
  return window['go']['main']['App']['GetUserStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function JoinRoom(arg1) {
  return window['go']['main']['App']['JoinRoom'](arg1);
}

export function LogStudySession(arg1, arg2) {
  return window['go']['main']['App']['LogStudySession'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PauseStudySession() {
  return window['go']['main']['App']['PauseStudySession']();
}

export function PlayGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlayGame'](arg1, arg2, arg3);
}

export function RejectFriendRequest(arg1) {
  return window['go']['main']['App']['RejectFriendRequest'](arg1);
}

export function ResumeStudySession() {
  return window['go']['main']['App']['ResumeStudySession']();
}

export function SaveTextToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveTextToDownloads'](arg1, arg2);
}

export function SendFriendRequest(arg1) {
  return window['go']['main']['App']['SendFriendRequest'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetIdleStatus(arg1) {
  return window['go']['main']['App']['SetIdleStatus'](arg1);
}

export function ShareResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShareResource'](arg1, arg2, arg3);
}

export function SignUp(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SignUp'](arg1, arg2, arg3, arg4, arg5);
}

export function StartStudySession(arg1, arg2) {
  return window['go']['main']['App']['StartStudySession'](arg1, arg2);
}

export function StopStudySession(arg1, arg2) {
  return window['go']['main']['App']['StopStudySession'](arg1, arg2);
}

export function ToggleGoalComplete(arg1) {
  return window['go']['main']['App']['ToggleGoalComplete'](arg1);
}

export function TrainRoomAI(arg1, arg2) {
  return window['go']['main']['App']['TrainRoomAI'](arg1, arg2);
}

export function UpdateAssignment(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateAssignment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateMilestoneProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateMilestoneProgress'](arg1, arg2);
}

export function UpdateMyProfile(arg1) {
  return window['go']['main']['App']['UpdateMyProfile'](arg1);
}

export function UpdateRoomExamDates(arg1, arg2) {
  return window['go']['main']['App']['UpdateRoomExamDates'](arg1, arg2);
}

export function UpdateRoomSyllabus(arg1, arg2) {
  return window['go']['main']['App']['UpdateRoomSyllabus'](arg1, arg2);
}

export function UpdateScheduleBlock(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateScheduleBlock'](arg1, arg2, arg3);
}

export function UpdateStudyPlanProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateStudyPlanProgress'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
